
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTBRACKET = 52;
  public static final int ASSIGNDIV = 49;
  public static final int FUNCTION = 9;
  public static final int READLINE = 23;
  public static final int RIGHTBRACKET = 53;
  public static final int DOUBLE = 3;
  public static final int INTEGER = 2;
  public static final int NOTEQUAL = 32;
  public static final int ASSIGNMUL = 48;
  public static final int GREATER = 34;
  public static final int PRIVATE = 29;
  public static final int CONTINUE = 16;
  public static final int ASSIGNADD = 46;
  public static final int LESS = 33;
  public static final int FOR = 11;
  public static final int STRINGCONST = 63;
  public static final int RIGHTPARANTHESIS = 56;
  public static final int DEFINE = 60;
  public static final int SEMICOLON = 50;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int READINTEGER = 22;
  public static final int LESSEQUAL = 35;
  public static final int INTCONST = 61;
  public static final int OR = 38;
  public static final int COMMA = 51;
  public static final int DOUBLECONST = 62;
  public static final int CLASS = 7;
  public static final int DIV = 40;
  public static final int NEWARRAY = 21;
  public static final int LEFTPARANTHESIS = 55;
  public static final int ASSIGN = 45;
  public static final int IF = 13;
  public static final int THIS = 19;
  public static final int DOT = 54;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 17;
  public static final int EQUAL = 31;
  public static final int RIGHTCURLY = 58;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int ADD = 42;
  public static final int LINE = 10;
  public static final int NULL = 20;
  public static final int MOD = 44;
  public static final int ASSIGNSUB = 47;
  public static final int BREAK = 15;
  public static final int VOID = 6;
  public static final int LEFTCURLY = 57;
  public static final int DTOI = 25;
  public static final int GREATEREQUAL = 36;
  public static final int IMPORT = 8;
  public static final int ELSE = 14;
  public static final int ITOD = 26;
  public static final int ITOB = 28;
  public static final int WHILE = 12;
  public static final int PUBLIC = 30;
  public static final int BOOLCONST = 64;
  public static final int BTOI = 27;
  public static final int STRING = 5;
  public static final int SUB = 43;
  public static final int PRINT = 24;
  public static final int IDENTIFIER = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "DOUBLE",
  "BOOLEAN",
  "STRING",
  "VOID",
  "CLASS",
  "IMPORT",
  "FUNCTION",
  "LINE",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "NEW",
  "THIS",
  "NULL",
  "NEWARRAY",
  "READINTEGER",
  "READLINE",
  "PRINT",
  "DTOI",
  "ITOD",
  "BTOI",
  "ITOB",
  "PRIVATE",
  "PUBLIC",
  "EQUAL",
  "NOTEQUAL",
  "LESS",
  "GREATER",
  "LESSEQUAL",
  "GREATEREQUAL",
  "AND",
  "OR",
  "NOT",
  "DIV",
  "MUL",
  "ADD",
  "SUB",
  "MOD",
  "ASSIGN",
  "ASSIGNADD",
  "ASSIGNSUB",
  "ASSIGNMUL",
  "ASSIGNDIV",
  "SEMICOLON",
  "COMMA",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "DOT",
  "LEFTPARANTHESIS",
  "RIGHTPARANTHESIS",
  "LEFTCURLY",
  "RIGHTCURLY",
  "IDENTIFIER",
  "DEFINE",
  "INTCONST",
  "DOUBLECONST",
  "STRINGCONST",
  "BOOLCONST"
  };
}

